### ISSUE TITLE
Member Join/Leave Custom Message and Channel

### ISSUE THREAD

**Issue by BeeBuzz420** [Cudiph/monotonebot#1]
It would be cool if you add the custom welcome message and leave message. It doesn't have to be embeded just plain text.

**Comment by Cudiph** [comment]
Thanks for the suggestion, that's a feature that I've wanted for a long time but I want it to be using embed and I didn't know the best way to parse argument from the message so I started getting lazy. If it's only a plain text maybe I can do it and maybe adding embed support in the future.

**Comment by BeeBuzz420** [comment]
> Thanks for the suggestion, that's a feature that I've wanted for a long time but I want it to be using embed and I didn't know the best way to parse argument from the message so I started getting lazy. If it's only a plain text maybe I can do it and maybe adding embed support in the future.

Well in my own opinion I prefer plain text. So It's up to you what you want.
